using UnityEngine;
using UnityEngine.Tilemaps;

namespace Flynn.Environment
{
    /// <summary>
    /// Keeps every <see cref="BillboardGrass"/> under the level loader pointed at the scene's grass
    /// mask.
    ///
    /// It exists because <c>JsonMapLoader.Regenerate()</c> DESTROYS and re-instantiates each
    /// <c>JsonLayerStack_*</c> from its styled template. Any mask reference assigned by hand on a
    /// stack is therefore gone the next time the level is rebuilt — silently, with the grass simply
    /// reverting to whole-island cover. Holding the references here, on the loader itself, and
    /// re-pushing them after every rebuild is what makes painted grass survive.
    ///
    /// Wire <c>JsonMapLoader.onRegenerated</c> → <see cref="Bind"/> and it maintains itself.
    /// </summary>
    [ExecuteAlways]
    public class GrassMaskBinder : MonoBehaviour
    {
        [Tooltip("The Tilemap you PAINT to say where grass grows. Paint a cell at Tile Palette " +
                 "Z = 1 to grow it on a level-1 terrace, Z = 2 for level 2, and so on.")]
        [SerializeField] private Tilemap grassMask;

        [Tooltip("Leave EMPTY to auto-collect every JsonLayer_* tilemap under the grid each time " +
                 "this binds. Those objects are generated by the loader, so a serialized reference " +
                 "to them cannot live on a prefab and would not survive a rebuild anyway.")]
        [SerializeField] private Tilemap[] platformMasks;

        [Tooltip("Grid holding the generated JsonLayer_* tilemaps. Auto-found under this object " +
                 "when empty.")]
        [SerializeField] private Grid grid;

        [Tooltip("Water paint masks, if any — water replaces the surface and culls blades.")]
        [SerializeField] private Tilemap[] waterMasks;

        [Tooltip("World Y per elevation level. MUST equal JsonMapLoader.heightStep or grass on a " +
                 "terrace lands at the wrong height.")]
        [SerializeField] private float elevationStep = 0.5f;

        [Tooltip("Push the mask into the base island's grass too, not just the raised stacks.")]
        [SerializeField] private bool includeBaseStack = true;

        [Tooltip("The BillboardGrass whose card sprites, material and look define the whole level " +
                 "(normally the base island's). Every other patch is copied from it on Bind. Leave " +
                 "EMPTY to let each patch keep its own cards — which is how one island ends up " +
                 "drawing new grass while the raised stacks still draw the template's old blades.")]
        [SerializeField] private BillboardGrass lookSource;

        [Tooltip("The level loader, so the generated stacks can be found. They no longer live under " +
                 "the rig — the loader parents them to its own scene-root container. Auto-found in " +
                 "children when empty.")]
        [SerializeField] private JsonMapLoader loader;

        [Header("Flora")]
        [Tooltip("The Tilemap you PAINT to say where FLORA grows — the hand-placed counterpart of the " +
                 "grass mask, on its own grid so plants and blades are authored independently. Paint " +
                 "a cell at Tile Palette Z = 1 to grow it on a level-1 terrace. Leave EMPTY to keep " +
                 "the old whole-island scatter.")]
        [SerializeField] private Tilemap floraMask;

        [Tooltip("Bind the flora mask into every IslandFoliage as well. Off = leave foliage alone.")]
        [SerializeField] private bool bindFlora = true;

        [Tooltip("The IslandFoliage whose prefab set and placement rules define the whole level " +
                 "(normally the base island's). Every other one is copied from it on Bind. Leave " +
                 "EMPTY to let each stack keep its own — which is how a hand-painted mask ends up " +
                 "growing plants on the base island but not on the terraces.")]
        [SerializeField] private IslandFoliage floraLookSource;

        [ContextMenu("Bind Grass Masks")]
        public void Bind()
        {
            var masks = platformMasks != null && platformMasks.Length > 0
                ? platformMasks
                : CollectGeneratedLayers();

            int bound = 0;
            foreach (var grass in CollectGrass())
            {
                if (grass == null) continue;
                if (!includeBaseStack && grass.SourceTilemap == null) continue;

                if (lookSource != null) grass.CopyLookFrom(lookSource);
                grass.SourceTilemap = grassMask;
                grass.ElevationStep = elevationStep;
                grass.PlatformMasks = masks;
                grass.WaterMasks = waterMasks;
                grass.Generate();
                bound++;
            }

            int flora = BindFlora(masks);

            if (grassMask == null)
                Debug.LogWarning("[GrassMaskBinder] No grass mask assigned — every BillboardGrass " +
                                 "fell back to whole-island cover.", this);
            else
                Debug.Log($"[GrassMaskBinder] Bound '{grassMask.name}' + {masks.Length} platform " +
                          $"mask(s) into {bound} BillboardGrass" +
                          (lookSource != null ? $", cards copied from '{lookSource.name}'" : "") +
                          $"; {flora} IslandFoliage on " +
                          (floraMask != null ? $"'{floraMask.name}'." : "whole-island scatter."), this);
        }

        /// <summary>
        /// Same deal for foliage: point every IslandFoliage at the hand-painted flora mask and give
        /// it the water/platform masks, so plants respect terraces and lakes exactly like the grass
        /// does. Separate mask from the grass one on purpose — where a plant may stand is a
        /// hand-authored decision, not a consequence of where blades cover.
        /// </summary>
        private int BindFlora(Tilemap[] masks)
        {
            if (!bindFlora) return 0;
            int bound = 0;
            foreach (var f in CollectFoliage())
            {
                if (f == null) continue;
                if (floraLookSource != null) f.CopyLookFrom(floraLookSource);
                if (floraMask != null) f.SourceTilemap = floraMask;
                f.ElevationStep = elevationStep;
                f.PlatformMasks = masks;
                f.WaterMasks = waterMasks;
                f.Generate();
                bound++;
            }
            return bound;
        }

        private System.Collections.Generic.List<IslandFoliage> CollectFoliage()
        {
            if (loader == null) loader = GetComponentInChildren<JsonMapLoader>(true);
            var found = new System.Collections.Generic.List<IslandFoliage>();
            found.AddRange(GetComponentsInChildren<IslandFoliage>(true));
            var generated = loader != null ? loader.GeneratedRoot : null;
            if (generated != null)
                foreach (var f in generated.GetComponentsInChildren<IslandFoliage>(true))
                    if (!found.Contains(f)) found.Add(f);
            return found;
        }

        /// <summary>
        /// Every patch in the level: the ones authored under the rig plus the ones the loader
        /// generated. The generated stacks sit under the loader's own scene-root container, so a
        /// children-only sweep misses exactly the patches that go stale.
        /// </summary>
        private System.Collections.Generic.List<BillboardGrass> CollectGrass()
        {
            if (loader == null) loader = GetComponentInChildren<JsonMapLoader>(true);
            var found = new System.Collections.Generic.List<BillboardGrass>();
            found.AddRange(GetComponentsInChildren<BillboardGrass>(true));
            var generated = loader != null ? loader.GeneratedRoot : null;
            if (generated != null)
                foreach (var g in generated.GetComponentsInChildren<BillboardGrass>(true))
                    if (!found.Contains(g)) found.Add(g);
            return found;
        }

        /// <summary>
        /// Every raised layer the loader generated, by the same name convention the rest of the
        /// module keys off. Collected fresh on each bind precisely because these objects are
        /// destroyed and rebuilt by Regenerate.
        /// </summary>
        private Tilemap[] CollectGeneratedLayers()
        {
            if (grid == null) grid = GetComponentInChildren<Grid>(true);
            if (grid == null) return System.Array.Empty<Tilemap>();

            var found = new System.Collections.Generic.List<Tilemap>();
            foreach (Transform child in grid.transform)
            {
                if (!child.name.StartsWith("JsonLayer_")) continue;
                var map = child.GetComponent<Tilemap>();
                if (map != null && map != grassMask) found.Add(map);
            }
            return found.ToArray();
        }
    }
}
