using UnityEditor;
using UnityEngine;
using UnityEngine.Tilemaps;

namespace Flynn.Modules.PlatformTiles
{
    /// <summary>
    /// Live-builder loop for platform collision/tiles: whenever a painted-layer cell map changes
    /// ("*_cells_z*", regenerated by PaintedStyleLayer — name-coupled, no loader dependency),
    /// rebuild every PlatformTileBuilder after a debounce. The builder's own collision output is
    /// named "PlatformCollision"/footprint, which the filter ignores — no rebuild loop.
    /// </summary>
    [InitializeOnLoad]
    public static class PlatformTilesLiveRebuild
    {
        private const double DebounceSeconds = 0.6;
        private static double _at;
        private static bool _pending;

        static PlatformTilesLiveRebuild()
        {
            Tilemap.tilemapTileChanged += OnTileChanged;
            EditorApplication.update += OnUpdate;
        }

        private static void OnTileChanged(Tilemap map, Tilemap.SyncTile[] tiles)
        {
            if (EditorApplication.isPlayingOrWillChangePlaymode) return;
            if (!map.name.Contains("_cells_z")) return;
            _at = EditorApplication.timeSinceStartup + DebounceSeconds;
            _pending = true;
        }

        private static void OnUpdate()
        {
            if (!_pending || EditorApplication.timeSinceStartup < _at) return;
            _pending = false;
            foreach (var b in Object.FindObjectsOfType<PlatformTileBuilder>(false))
                b.BuildTiles();
        }
    }
}
